"""message

Revision ID: d9d9f188e362
Revises: b3bc3883bab7
Create Date: 2025-02-05 16:01:15.154985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d9f188e362'
down_revision = 'b3bc3883bab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
